#!/usr/bin/env bash

#MISE description="Format source code"

#USAGE flag "--mode <mode>" {
#USAGE   choices "check" "write"
#USAGE   default "check"
#USAGE   help "Format mode"
#USAGE }

set -ueC
set -o pipefail

npm exec -- prettier "--${usage_mode?}" --cache --cache-location='.prettier/cache' --cache-strategy content .

terraform fmt -"${usage_mode?}" -recursive .github/environments/
