name: "Install Sync Settings CLI"
description: "Installs the Sync Settings CLI"
runs:
  using: "composite"
  steps:
    - name: Install Package
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm ci
        npm i -g
