name: "Release NPM Package"
description: "Runs Semantic Release to publish a new npm package version"
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci

    - name: Extract Package Metadata
      shell: bash
      run: |
        PKG_NAME=$(jq -r '.name | split("/") | .[1]' ./package.json)
        echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV

    - name: Run Semantic Release
      shell: bash
      env:
        RELEASE_CLI_DIR: ${{ github.action_path }}
      run: ${{ github.action_path }}/node_modules/.bin/semantic-release
