name: "Clone Repo"
description: "Clone this repository"
inputs:
  repo_name:
    description: "Repository name"
    required: true
  template_branch:
    description: "Template branch to persist in the new repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone Repo
      shell: bash
      env:
        CLONE_REPO_NAME: ${{ inputs.repo_name }}
        SOURCE_REPO_NAME: ${{ github.event.repository.name }}
        TEMPLATE_BRANCH: ${{ inputs.template_branch }}
      run: |
        mise run ${{ github.action_path }}/clone-repo.sh
