name: "Install Clone Repo CLI"
description: "Installs the Clone Repo CLI"
runs:
  using: "composite"
  steps:
    - name: Install Package
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm ci
        npm i -g
        mise trust -q
        mise install
        mise bin-paths >> "$GITHUB_PATH"
