include:
  - ./compose.otel.yml

x-config:
  terraform_plugin_cache_path: &terraform_plugin_cache_path /root/.terraform.d/plugin-cache

volumes:
  node_modules:
  terraform_env_workspace:
  local_bin:
  mise_data:
    name: shared-mise-data
  npm_cache:
    name: shared-npm-cache
  terraform_plugin_cache:
    name: shared-terraform-plugin-cache

services:
  devcon:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04

    # Keep container running indefinitely
    command: sleep infinity

    environment:
      TF_PLUGIN_CACHE_DIR: *terraform_plugin_cache_path
      MISE_ENV: dev
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/dbus-proxy/secrets.sock
      GITHUB_USERNAME: ${GITHUB_USERNAME:?GITHUB_USERNAME not set}

    # Mount project folder and Docker socket
    volumes:
      - ..:/workspace
      - ./devcon/.config/mise:/root/.config/mise
      - ./devcon/profile.d/mise-tokens.sh:/etc/profile.d/mise-tokens.sh
      - ./runtime:/run/dbus-proxy
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ${HOME}/.terraform.d/credentials.tfrc.json:/root/.terraform.d/credentials.tfrc.json

      - node_modules:/workspace/node_modules
      - terraform_env_workspace:/workspace/.github/environments/.terraform
      - local_bin:/root/.local/bin

      - mise_data:/root/.local/share/mise
      - npm_cache:/root/.npm
      - type: volume
        source: terraform_plugin_cache
        target: *terraform_plugin_cache_path

    env_file:
      - ./devcon/.env
    networks:
      - otel
