[settings]
# locked = true

[tasks."ci:check"]
run.tasks = ["format", "test --mode=unit", "lint"]

[tasks."ci:build"]
depends = ["ci:check"]
run.tasks = ["assets"]

[tasks.ci]
depends = ["ci:build"]
run.tasks = ["test --mode=integration"]
