[env]
_.source = "./.mise/source.sh"

[tools]
usage = "3"
terraform = "1"
"github:cli/cli" = "2"
"github:hadolint/hadolint" = "2"
"npm:husky" = "9"
"npm:@commitlint/cli" = "20"
"yq" = "4"
"github:comby-tools/comby" = { version = "1", asset_pattern = "comby-*-x86_64-linux.tar.gz", rename_exe = "comby", "bin_path" = "." }
