[settings]
lockfile = true

[tools]
node = "24"
npm = "11"

[tasks.install]
file = "./tasks/install.sh"

[tasks.test]
file = "./tasks/test.sh"

[tasks.assets]
file = "./tasks/assets.sh"

[tasks.format]
file = "./tasks/format.sh"

[tasks.lint]
file = "./tasks/lint.sh"

[tasks.clean]
file = "./tasks/clean.sh"

[tasks.check]
run.tasks = ["format", "test --mode=unit", "lint"]

[tasks.build]
run.tasks = ["check", "assets"]

[tasks.integrate]
depends = ["build"]
run.tasks = ["test --mode=integration"]
