[settings]
lockfile = true

[tools]
node = "24"
npm = "11"

[tasks.check]
run.tasks = ["format", "test --mode=unit", "lint"]

[tasks.build]
run.tasks = ["check", "assets"]

[tasks.integrate]
depends = ["build"]
run.tasks = ["test --mode=integration"]
