name: CD

on:
  push:
    branches: [main]
    paths:
      - "**"

concurrency:
  group: "CD"
  cancel-in-progress: false

permissions:
  packages: write

env:
  BOT_NAME: "${{ vars.DELIVERY_APP_NAME }}[bot]"
  BOT_EMAIL: "${{vars.DELIVERY_ACTOR_ID}}+${{vars.DELIVERY_APP_SLUG}}[bot]@users.noreply.github.com"
  MISE_ENV: cd

jobs:
  cd:
    name: CD
    if: (github.actor_id != vars.DELIVERY_ACTOR_ID)
    environment: GitHub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v3
        id: token
        with:
          app-id: ${{ vars.DELIVERY_APP_ID }}
          private-key: ${{ secrets.DELIVERY_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.token.outputs.token }}
      - uses: jdx/mise-action@v4
      - name: Install Release CLI
        uses: ./.github/actions/release
      - name: CD
        run: |
          mise run cd
          npm-release \
            --github-pkg-token "${{ secrets.GITHUB_TOKEN }}" \
            --github-token "${{ steps.token.outputs.token }}" \
            --git-author-name "${{ env.BOT_NAME }}" \
            --git-author-email "${{ env.BOT_EMAIL }}"
