name: Clone Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name"
        required: true

concurrency:
  group: "Clone Repo"
  cancel-in-progress: false

jobs:
  clone-repo:
    name: Clone Repository - '${{ github.event.inputs.repo_name }}'
    environment: GitHubAdmin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.ADMIN_APP_ID }}
          private-key: ${{ secrets.ADMIN_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}
          permission-administration: write
          permission-contents: write
          permission-repository-custom-properties: write
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.token.outputs.token }}
      - uses: jdx/mise-action@v4
      - uses: ./.github/actions/clone-repo
      - uses: ./.github/actions/sync-settings
      - name: Clone Repo
        run: |
          clone-repo \
            --repo-name "${{ github.event.inputs.repo_name }}" \
            --repo-owner "${{ github.repository_owner }}" \
            --source-repo-name "${{ github.event.repository.name }}" \
            --template-branch "${{ vars.TEMPLATE_BRANCH }}" \
            --github-token "${{ steps.token.outputs.token }}" \
            --tf-org-token "${{ secrets.ADMIN_TF_ORG_API_TOKEN }}" \
            --tf-project-id "${{ vars.ADMIN_TF_PROJECT_ID }}" \
            --tf-org-name "${{ vars.ADMIN_TF_ORG_NAME }}" \
            --workspace-dir "${{ github.workspace }}"
      - name: Sync Settings
        run: |
          sync-settings \
            --repo-name "${{ github.event.inputs.repo_name }}" \
            --repo-owner "${{ github.repository_owner }}" \
            --tf-token "${{ secrets.ADMIN_TF_API_TOKEN }}" \
            --github-token "${{ steps.token.outputs.token }}"
