name: Sync Repo Settings

on:
  workflow_dispatch:

concurrency:
  group: "Sync Repo Settings"
  cancel-in-progress: false

jobs:
  sync-repo-settings:
    name: Sync Repository Settings
    environment: GitHubAdmin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.ADMIN_APP_ID }}
          private-key: ${{ secrets.ADMIN_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-administration: write
          permission-contents: read
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.token.outputs.token }}
      - uses: jdx/mise-action@v4
      - uses: ./.github/actions/sync-settings
      - name: Sync Settings
        run: |
          sync-settings \
            --repo-name "${{ github.event.repository.name }}" \
            --repo-owner "${{ github.repository_owner }}" \
            --tf-token "${{ secrets.ADMIN_TF_API_TOKEN }}" \
            --github-token "${{ steps.token.outputs.token }}"
